### ISSUE TITLE
eix-0.33.0 - undefined references

### ISSUE THREAD

**Issue by rain0r** [vaeth/mv-overlay#2] opened 2017-08-23 07:46 UTC
I get this error messages when emerging eix-0.33.0:

```
/var/tmp/portage/app-portage/eix-0.33.0/temp/ccDrlQWW.lto.o: In function `eix::format& eix::format::operator%<char const*>(char const* const&) [clone .constprop.1]':
<artificial>:(.text._ZN3eix6formatrmIPKcEERS0_RKT_.constprop.1+0xf0): undefined reference to `eix::format::newline_output()'
<artificial>:(.text._ZN3eix6formatrmIPKcEERS0_RKT_.constprop.1+0x1dd): undefined reference to `eix::format::too_many_arguments() const'
<artificial>:(.text._ZN3eix6formatrmIPKcEERS0_RKT_.constprop.1+0x1e5): undefined reference to `eix::format::finalize()'
/var/tmp/portage/app-portage/eix-0.33.0/temp/ccDrlQWW.lto.o: In function `sig_handler(int)':
<artificial>:(.text._ZL11sig_handleri+0xa4): undefined reference to `eix::format::init()'
/var/tmp/portage/app-portage/eix-0.33.0/temp/ccDrlQWW.lto.o: In function `main':
<artificial>:(.text.startup.main+0xf8): undefined reference to `to_lower(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
<artificial>:(.text.startup.main+0x16f): undefined reference to `run_eix_drop_permissions(int, char**)'
<artificial>:(.text.startup.main+0x1c2): undefined reference to `run_eix_diff(int, char**)'
<artificial>:(.text.startup.main+0x1cf): undefined reference to `run_eix_update(int, char**)'
<artificial>:(.text.startup.main+0x218): undefined reference to `run_masked_packages(int, char**)'
<artificial>:(.text.startup.main+0x244): undefined reference to `run_eix_header(int, char**)'
<artificial>:(.text.startup.main+0x270): undefined reference to `run_versionsort(int, char**)'
<artificial>:(.text.startup.main+0x2b4): undefined reference to `run_eix(int, char**)'
```

Full build.log is available here: https://gist.github.com/rain0r/cb3180f8bb9735d28d7af13fe1a7837e

Use-Flags:
`[ebuild     U ] app-portage/eix-0.33.0 [0.32.10] USE="dep meson%* required-use strong-optimization -debug -doc -nls -optimization -security -sqlite -strong-sec`

emerge --info: https://gist.github.com/rain0r/ba227f7d0d69ec6379b61ad4e6f62bfa

**Comment by vaeth** [comment] 2017-08-23 16:18
The problem is that USE=strong-optimiziation sets the -flto flag which due to meson's requirements of using static libs does not work without linker plugin.

In the moment, I do not have a good idea how to solve this issue from within the ebuild. You can either disable strong-optimization or avoid meson. The best solution, however, is to enable the linker plugin:

On an amd64 system, execute
```ln -s  /usr/libexec/gcc/x86_64-pc-linux-gnu/*/liblto_plugin.so.0.0.0 /usr/x86_64-pc-linux-gnu/binutils-bin/lib/bfd-plugins```
(replacing * by your currently used compiler version), and on an x86 system execute
```ln -s /usr/libexec/gcc/i686-pc-linux-gnu/*/liblto_plugin.so.0.0.0 /usr/i686-pc-linux-gnu/binutils-bin/lib/bfd-plugins```

**Comment by vaeth** [comment] 2017-08-23 18:02
In the lack of a proper fix, currently, the ebuild prints now instructions similar to above if USE="strong-optimization meson" are both enabled and if a heurstics shows that the plugin is not available.

**Comment by olifre** [comment] 2017-08-25 19:54
> In the lack of a proper fix, currently, the ebuild prints now instructions similar to above if USE="strong-optimization meson" are both enabled and if a heurstics shows that the plugin is not available.

The ebuild now sadly calls `die` **unless** `USE="strong-optimization meson"` is set, and the heuristics if fulfilled. 
This means building without meson and strong-optimization will now fail - since the error messages and `die` are outside of the `if` statement...

**Comment by vaeth** [comment] 2017-08-25 20:11
Thanks for pointing out the stupid mistake; should be fixed now.
I will leave the bug open until I either find a better solution than the current hack or give up...

**Comment by vaeth** [comment] 2017-09-05 09:05
As I remarked on the above mentioned meson bug, I am no longer able to reproduce the problem.
Therefore, I transformed the fatal error into just a warning message in eix-0.33.0.

For the alpha and live versions, I have written a more sophisticated test.

For the case that some of you can still reproduce the problem (i.e. after removing the symlink in `/usr/*/binutils-bin/lib/bfd-plugins/liblto_plugin.so.0.0.0`), I would appreciate if you can test whether this test is correct, i.e. whether you already receive an instructive error message near the beginning of the emerge, or whether as before you receive only an error during linking at the very end.
(As mentioned above, I do not receive any error at all, anymore, so I cannot verify the test myself...)

Thanks in advance.

**Comment by vaeth** [comment] 2017-09-06 09:05
Finally, I can reproduce the problem again (see the above mentioned meson bug for details).

The more sophisticated test should now be working (except perhaps in some exotic situations like cross-compiling).

Anyway, I will leave the bug open until it is properly fixed (which probably can only be done if either gentoo adds support for lto plugins into e.g. gcc-config or if meson provides a way to avoid the redundant use of static archives).

**Comment by vaeth** [comment] 2018-03-21 07:19
Closing now since gentoo added support for lto plugins to gcc-config.

**Closed by vaeth** 2018-03-21 07:19 UTC
