### ISSUE TITLE
32-bit Gtk+2 causes dependency conflicts

### ISSUE THREAD

**Issue by Althorion** [vaeth/mv-overlay#19] opened 2020-07-07 20:56 UTC
When I try to update my system after enabling this overlay, updating the system fails with the following dependency conflict:
```
emerge -puDNv @world --autounmask-backtrack=y

These are the packages that would be merged, in order:

Calculating dependencies      ... done!          
[ebuild     U  ] app-shells/push-3.1-r4::mv [2.0-r1::gentoo] USE="(split-usr%*)" 0 KiB
[ebuild     U  ] app-shells/quoter-4.1-r1::mv [3.0_p2-r1::gentoo] 0 KiB
[ebuild   R    ] dev-libs/protobuf-3.12.2:0/23::gentoo  USE="zlib -emacs -examples -static-libs -test" ABI_X86="32* (64) (-x32)" 0 KiB
[ebuild   R    ] sys-apps/less-563::mv [563::gentoo] USE="less-select%* lesspipe%* pcre unicode -original-gentoo% -source%" 0 KiB
[ebuild     UD ] dev-lang/python-3.7.7-r2:3.7/3.7m::mv [3.7.7-r3:3.7/3.7m::lto-overlay] USE="bluetooth* gdbm ipv6 ncurses readline sqlite ssl xml -build -examples -hardened -libressl -test -tinfo% -tk -wininst (-pgo%)" 0 KiB
[ebuild   R    ] app-portage/eix-0.34.4::mv [0.34.4::gentoo] USE="dep%* jumbo-build%* meson%* nls protobuf%* required-use%* src-uri%* -debug -doc -optimization% -security% -sqlite -strong-optimization% -strong-security% -swap-remote% -tools% -usr-portage%" L10N="-de% -ru%" 0 KiB
[ebuild   R    ] x11-libs/gtk+-3.24.21:3::mv [3.24.21:3::gentoo] USE="X cups introspection wayland -adwaita-icon-theme% (-aqua) -atk-bridge% -broadway -cloudprint -colord -examples -gtk-doc -test -vim-syntax -xinerama" ABI_X86="32 (64) (-x32)" 0 KiB
[ebuild   R    ] app-text/djvu-3.5.27-r2::gentoo  USE="jpeg* tiff* xml* -debug -doc" 0 KiB
[ebuild   R    ] app-text/lesspipe-1.85_alpha20200517::mv  USE="cpio djvu dvi2tty elinks ghostscript groff html2text links lynx pdf* rpm2targz unzip w3m zstd -antiword -brotli -cabextract -catdoc -dpkg -exiftool -fastjar -gpg -hdf5 -id3v2 -image -isoinfo -libplist -libreoffice -lz4 -lzip -mediainfo -mp3info -mp3info2 -netcdf -ooffice -p7zip -pandoc -pstotext -rar -rpm -unrar -unrtf -wv -xlhtml" 0 KiB

Total: 9 packages (2 upgrades, 1 downgrade, 6 reinstalls), Size of downloads: 0 KiB

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

x11-libs/gtk+:2

  (x11-libs/gtk+-2.24.32-r1:2/2::mv, ebuild scheduled for merge) USE="cups introspection -adwaita-icon-theme (-aqua) -doc -examples -test -vim-syntax -xinerama" ABI_X86="(64) -32 (-x32)" conflicts with
    >=x11-libs/gtk+-2.18:2[abi_x86_32(-),abi_x86_64(-)] required by (x11-libs/wxGTK-3.0.4-r2:3.0/3.0::gentoo, installed) USE="X libnotify opengl sdl tiff (-aqua) -debug -doc -gstreamer" ABI_X86="32 (64) (-x32)"
                                                       
    x11-libs/gtk+:2[abi_x86_32,cups] required by (games-util/steam-client-meta-0-r20200328:0/0::steam-overlay, installed) USE="pulseaudio -flash -steamfonts -steamruntime -steamvr -trayicon" ABI_X86="(64)" VIDEO_CARDS="-intel -nvidia"
                    ^^^^^^^^^^      
    >=x11-libs/gtk+-2.24.23:2[abi_x86_32(-),abi_x86_64(-)] required by (x11-themes/gtk-engines-murrine-0.98.2-r1:0/0::gentoo, installed) USE="themes -animation-rtl" ABI_X86="32 (64) (-x32)"
                                                          
    >=x11-libs/gtk+-2.24.15:2[abi_x86_32(-),abi_x86_64(-)] required by (x11-themes/gtk-engines-adwaita-3.28:0/0::gentoo, installed) USE="" ABI_X86="32 (64) (-x32)"
```

I masked the package for now, and that seems to have worked.

**Comment by vaeth** [comment] 2020-07-10 18:24
Thanks for the report. Presumably, this was caused by a bad USE-dependency on virtual/pkgconf which should be fixed now.

**Closed by vaeth** 2020-07-10 18:24 UTC
